### ISSUE TITLE
Party Mode

### ISSUE THREAD

**Issue by Aschenbecher** [prowley/SteaSummon#47]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to port in a pary and have to do it manually :D

**Describe the solution you'd like**
just working in party aswell

Thanks for the great addon, keep it going!

**Comment by prowley** [comment]
Which part doesn't work in a party for you? Parties have always been supported. I don't end up in parties a lot myself these days, but I just set up a test and at least getting added to the summon list and summoning works as intended when in a party. Is this more a feature request? Like, have party members not in your location added to the list or something?

**Comment by Aschenbecher** [comment]
Yes, sorry, it´s working! you can close it 🥇
